import { useState, useCallback, useRef } from 'react';

export const LANGUAGES = [
  { code: 'id', label: 'Indonesian' },
  { code: 'zh', label: 'Chinese (Simplified)' },
  { code: 'es', label: 'Spanish' },
  { code: 'fr', label: 'French' },
  { code: 'de', label: 'German' },
  { code: 'ja', label: 'Japanese' },
  { code: 'ko', label: 'Korean' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'ar', label: 'Arabic' },
  { code: 'hi', label: 'Hindi' },
];

/**
 * useAITranslation
 *
 * Uses Chrome's built-in AI APIs to translate Bible verses entirely on-device.
 * Priority order:
 *   1. window.translation (Translation API – Chrome 138+)
 *   2. window.ai.languageModel (Prompt API / Gemini Nano – Chrome 127+)
 *
 * ⚠️  Translations are generated by an on-device AI model (Google Gemini Nano).
 *     Accuracy is not guaranteed. The website bears no responsibility for
 *     any mistranslations.
 */
export function useAITranslation() {
  const [translation, setTranslation] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [targetLang, setTargetLang] = useState('id');
  const sessionRef = useRef(null);

  const translate = useCallback(async (text, lang) => {
    const useLang = lang ?? targetLang;
    if (!text) return;

    // destroy previous session
    if (sessionRef.current) {
      try { sessionRef.current.destroy(); } catch (_) {}
      sessionRef.current = null;
    }

    setLoading(true);
    setError(null);
    setTranslation('');

    try {
      // ── 1. Try Translation API (Chrome 138+) ──────────────────────────────
      if (typeof window !== 'undefined' && 'translation' in window) {
        try {
          const canTranslate = await window.translation.canTranslate({
            sourceLanguage: 'en',
            targetLanguage: useLang,
          });

          if (canTranslate !== 'no') {
            if (canTranslate === 'after-download') {
              // model needs to download first – wait for it
              const translator = await window.translation.createTranslator({
                sourceLanguage: 'en',
                targetLanguage: useLang,
              });
              await translator.ready;
              const result = await translator.translate(text);
              setTranslation(result);
              return;
            } else {
              const translator = await window.translation.createTranslator({
                sourceLanguage: 'en',
                targetLanguage: useLang,
              });
              const result = await translator.translate(text);
              setTranslation(result);
              return;
            }
          }
        } catch (translationErr) {
          // fall through to Prompt API
          console.warn('[AI Translation] Translation API failed, falling back to Prompt API:', translationErr);
        }
      }

      // ── 2. Fallback: Prompt API / Gemini Nano (Chrome 127+) ───────────────
      if (typeof window !== 'undefined' && window?.ai?.languageModel) {
        const langLabel = LANGUAGES.find(l => l.code === useLang)?.label ?? useLang;

        const session = await window.ai.languageModel.create({
          systemPrompt: [
            `You are a Bible verse translator.`,
            `Translate the given English Bible text into ${langLabel}.`,
            `Output ONLY the translated text — no explanations, no notes, no commentary.`,
            `Preserve verse numbers exactly as they appear (e.g. "1 In the beginning…" stays numbered).`,
          ].join(' '),
        });
        sessionRef.current = session;

        const result = await session.prompt(
          `Translate the following Bible verse(s) to ${langLabel}:\n\n${text}`
        );
        setTranslation(result.trim());
        return;
      }

      // ── 3. Not available ──────────────────────────────────────────────────
      setError(
        'Chrome Built-in AI is not available on this browser. ' +
        'Please use Chrome 127 or later and enable AI features in chrome://flags.'
      );
    } catch (err) {
      setError('Translation failed: ' + (err?.message ?? String(err)));
    } finally {
      setLoading(false);
    }
  }, [targetLang]);

  const clear = useCallback(() => {
    setTranslation('');
    setError(null);
    if (sessionRef.current) {
      try { sessionRef.current.destroy(); } catch (_) {}
      sessionRef.current = null;
    }
  }, []);

  return { translation, loading, error, targetLang, setTargetLang, translate, clear };
}
