import React, { useState, useCallback } from 'react';
import { useAITranslation, LANGUAGES } from '../src/hooks/useAITranslation';

function TranslationPanel({ translation, loading, error, onClose }) {
  return (
    <div className="mt-2 rounded-xl border border-amber-200 bg-amber-50/60 px-4 py-3 flex flex-col gap-2 text-sm">
      {/* disclaimer */}
      <p className="text-[10px] text-amber-700/70 leading-tight">
        ⚠️ This translation is generated by <strong>Google Gemini Nano</strong> running entirely on your device.
        It may contain errors. The website bears <strong>no responsibility</strong> for mistranslations.
        Always verify with a trusted Bible translation.
      </p>

      {loading && (
        <p className="text-amber-700 animate-pulse text-xs text-center py-2">Translating…</p>
      )}
      {error && (
        <p className="text-red-500 text-xs">{error}</p>
      )}
      {translation && !loading && (
        <p className="text-gray-800 leading-relaxed" style={{ lineHeight: 1.75 }}>
          {translation}
        </p>
      )}

      <button
        onClick={onClose}
        className="self-end text-[10px] text-amber-700/60 hover:text-amber-900 transition"
      >
        ✕ Close translation
      </button>
    </div>
  );
}

export function VerseCard({ reference, loading, verse, verses, error, speaking, onSpeak, onCopy, copied, onPresent }) {
  const { translation, loading: aiLoading, error: aiError, targetLang, setTargetLang, translate, clear } = useAITranslation();
  const [showTranslate, setShowTranslate] = useState(false);

  const verseText = verses.length > 1
    ? verses.map(({ verse: n, text }) => `${n} ${text}`).join('\n')
    : verse;

  const handleTranslate = useCallback((lang) => {
    translate(verseText, lang);
  }, [translate, verseText]);

  const handleLangChange = useCallback((e) => {
    setTargetLang(e.target.value);
    if (showTranslate) translate(verseText, e.target.value);
  }, [setTargetLang, showTranslate, translate, verseText]);

  const toggleTranslate = useCallback(() => {
    if (showTranslate) {
      setShowTranslate(false);
      clear();
    } else {
      setShowTranslate(true);
      handleTranslate(targetLang);
    }
  }, [showTranslate, clear, handleTranslate, targetLang]);

  const hasVerse = !loading && (verse || verses.length > 0) && !error;

  return (
    <article className="w-full glass rounded-2xl px-4 sm:px-6 py-4 sm:py-5 flex flex-col gap-3 animate-fade-up delay-200">
      {/* ── Header row: wraps on mobile ── */}
      <div className="flex flex-wrap items-center gap-y-2 gap-x-2">
        <span className="text-xs font-bold tracking-widest uppercase text-amber-700 mr-auto">
          📖 {reference || '—'}
        </span>
        {loading && (
          <span className="text-xs text-black/30 animate-pulse">Loading…</span>
        )}
        {!loading && verse && (
          <div className="flex items-center gap-1.5">
            <button
              onClick={onPresent}
              title="Teleprompter view"
              className="text-xs px-3 py-1.5 rounded-lg border border-black/10 text-black/50 hover:text-black/80 hover:border-black/25 active:scale-95 transition-all"
            >
              ⛶ Present
            </button>
            <button
              onClick={onSpeak}
              title={speaking ? 'Stop reading' : 'Read aloud'}
              className="text-xs px-3 py-1.5 rounded-lg border border-black/10 text-black/50 hover:text-black/80 hover:border-black/25 active:scale-95 transition-all"
            >
              {speaking ? '⏹ Stop' : '🔊 Read'}
            </button>
            <button
              onClick={onCopy}
              title="Copy verse"
              className="text-xs px-3 py-1.5 rounded-lg border border-black/10 text-black/50 hover:text-black/80 hover:border-black/25 active:scale-95 transition-all"
            >
              {copied ? '✓ Copied' : 'Copy'}
            </button>
          </div>
        )}
      </div>

      {error ? (
        <p className="text-red-500 text-sm text-center">{error}</p>
      ) : loading ? (
        <p className="animate-pulse text-black/30 text-sm text-center py-4">Loading verse…</p>
      ) : verses.length > 1 ? (
        <ol className="flex flex-col gap-2 text-gray-800 text-sm leading-relaxed list-none">
          {verses.map(({ verse: num, text }) => (
            <li key={num} className="flex gap-2">
              <span className="text-amber-600 font-bold text-xs mt-0.5 min-w-[1.5rem]">{num}</span>
              <span>{text}</span>
            </li>
          ))}
        </ol>
      ) : (
        <p className="text-gray-800 leading-relaxed text-base text-center min-h-[56px]" style={{ fontFamily: 'Inter, sans-serif', letterSpacing: '0.01em', lineHeight: 1.75 }}>
          {verse}
        </p>
      )}

      {/* ── AI Translate toolbar ── */}
      {hasVerse && (
        <div className="flex flex-wrap items-center gap-2 pt-1 border-t border-black/5">
          <select
            value={targetLang}
            onChange={handleLangChange}
            className="flex-1 min-w-0 text-xs rounded-lg border border-black/10 text-black/50 bg-transparent px-2 py-1.5 hover:border-black/25 transition-all focus:outline-none"
          >
            {LANGUAGES.map(({ code, label }) => (
              <option key={code} value={code}>{label}</option>
            ))}
          </select>
          <button
            onClick={toggleTranslate}
            title="Translate with on-device AI (Google Gemini Nano)"
            className={`text-xs px-3 py-1.5 rounded-lg border transition-all active:scale-95 whitespace-nowrap ${
              showTranslate
                ? 'border-amber-400 text-amber-700 bg-amber-50'
                : 'border-black/10 text-black/50 hover:text-black/80 hover:border-black/25'
            }`}
          >
            {aiLoading ? '⏳ Translating…' : '🌐 AI Translate'}
          </button>
          <span className="hidden sm:inline text-[10px] text-black/25 ml-auto whitespace-nowrap">Gemini Nano · on-device</span>
        </div>
      )}

      {/* ── Translation result ── */}
      {showTranslate && (
        <TranslationPanel
          translation={translation}
          loading={aiLoading}
          error={aiError}
          onClose={toggleTranslate}
        />
      )}
    </article>
  );
}
