import React, { useState, useCallback } from 'react';
import { useAITranslation, LANGUAGES } from '../hooks/useAITranslation';
import { useWebFeaturesStore } from '../stores/webFeaturesStore';
import { useSettingsStore } from '../stores/settingsStore';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faGlobe,
  faSpinner,
  faXmark,
  faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons';

const FONT_SIZE_MAP = {
  sm: 16,
  md: 18,
  lg: 21,
  xl: 24,
};

/**
 * Derive which translation mode is available from webFeaturesStore state.
 * Returns: 'gemini' | 'translation-api' | null
 */
function useTranslationMode() {
  const geminiNano = useWebFeaturesStore((s) => s.geminiNano);
  const translationApi = useWebFeaturesStore((s) => s.translationApi);
  if (geminiNano !== 'unavailable') return 'gemini'; // ready / needs-download / unknown / checking
  if (translationApi !== 'unavailable') return 'translation-api'; // same
  return null; // both confirmed unavailable → hide UI
}

function TranslationPanel({
  translation,
  loading,
  error,
  onClose,
  mode,
  contentFontFamily,
  contentFontSize,
}) {
  return (
    <div className="mt-2 rounded-xl border border-amber-200 bg-amber-50/60 px-4 py-3 flex flex-col gap-2 text-sm">
      {mode === 'gemini' && (
        <p className="text-[10px] text-amber-700/70 leading-tight">
          <FontAwesomeIcon icon={faTriangleExclamation} className="mr-1" />
          This translation is generated by <strong>
            Google Gemini Nano
          </strong>{' '}
          running entirely on your device. It may contain errors. The website
          bears <strong>no responsibility</strong> for mistranslations. Always
          verify with a trusted Bible translation.
        </p>
      )}

      {loading && (
        <p className="text-amber-700 animate-pulse text-xs text-center py-2">
          Translating…
        </p>
      )}
      {error && <p className="text-red-500 text-xs">{error}</p>}
      {translation && !loading && (
        <p
          className="text-gray-800 leading-relaxed"
          style={{
            fontSize: Math.max(14, contentFontSize - 2),
            fontFamily: contentFontFamily,
            lineHeight: 1.75,
          }}
        >
          {translation}
        </p>
      )}

      <button
        onClick={onClose}
        className="self-end text-[10px] text-amber-700/60 hover:text-amber-900 transition"
      >
        <FontAwesomeIcon icon={faXmark} className="mr-1" />
        Close translation
      </button>
    </div>
  );
}

/**
 * TranslationSection — AI Translate toolbar + result panel (light theme).
 *
 * @param {{ verseText: string }} props
 */
export function TranslationSection({ verseText }) {
  const mode = useTranslationMode();
  const fontFamily = useSettingsStore((s) => s.fontFamily);
  const fontSize = useSettingsStore((s) => s.fontSize);
  const contentFontFamily =
    fontFamily === 'serif' ? "'Playfair Display', serif" : 'Inter, sans-serif';
  const contentFontSize = FONT_SIZE_MAP[fontSize] ?? FONT_SIZE_MAP.md;
  const {
    translation,
    loading,
    error,
    targetLang,
    setTargetLang,
    translate,
    clear,
  } = useAITranslation();

  const [showTranslate, setShowTranslate] = useState(false);

  const handleTranslate = useCallback(
    (lang) => {
      translate(verseText, lang);
    },
    [translate, verseText]
  );

  const handleLangChange = useCallback(
    (e) => {
      setTargetLang(e.target.value);
      if (showTranslate) translate(verseText, e.target.value);
    },
    [setTargetLang, showTranslate, translate, verseText]
  );

  const toggleTranslate = useCallback(() => {
    if (showTranslate) {
      setShowTranslate(false);
      clear();
    } else {
      setShowTranslate(true);
      handleTranslate(targetLang);
    }
  }, [showTranslate, clear, handleTranslate, targetLang]);

  if (!mode) return null;

  const btnLabel = mode === 'gemini' ? 'AI Translate' : 'Translate';

  return (
    <>
      {/* ── AI Translate toolbar ── */}
      <div className="flex flex-wrap items-center gap-2 pt-1 border-t border-black/5">
        <select
          value={targetLang}
          onChange={handleLangChange}
          className="flex-1 min-w-0 text-xs rounded-lg border border-black/10 text-black/50 bg-transparent px-2 py-1.5 hover:border-black/25 transition-all focus:outline-none"
        >
          {LANGUAGES.map(({ code, label }) => (
            <option key={code} value={code}>
              {label}
            </option>
          ))}
        </select>
        <button
          onClick={toggleTranslate}
          title="Translate with on-device AI (Google Gemini Nano)"
          className={`text-xs px-3 py-1.5 rounded-lg border transition-all active:scale-95 whitespace-nowrap ${
            showTranslate
              ? 'border-amber-400 text-amber-700 bg-amber-50'
              : 'border-black/10 text-black/50 hover:text-black/80 hover:border-black/25'
          }`}
        >
          {loading ? (
            <>
              <FontAwesomeIcon icon={faSpinner} spin className="mr-1" />
              Translating…
            </>
          ) : (
            <>
              <FontAwesomeIcon icon={faGlobe} className="mr-1" />
              {btnLabel}
            </>
          )}
        </button>
        <span className="hidden sm:inline text-[10px] text-black/25 ml-auto whitespace-nowrap">
          Gemini Nano · on-device
        </span>
      </div>

      {/* ── Translation result ── */}
      {showTranslate && (
        <TranslationPanel
          translation={translation}
          loading={loading}
          error={error}
          onClose={toggleTranslate}
          mode={mode}
          contentFontFamily={contentFontFamily}
          contentFontSize={contentFontSize}
        />
      )}
    </>
  );
}

/**
 * TeleprompterTranslationSection — dark-themed AI Translate toolbar + result panel.
 * Designed to sit in the Teleprompter content area below the verse block.
 *
 * @param {{ pageText: string, fontSize: number, btnCls: string, selectBg: string }} props
 */
export function TeleprompterTranslationSection({
  pageText,
  fontSize,
  fontFamily,
  btnCls,
  selectBg,
}) {
  const mode = useTranslationMode();
  const {
    translation,
    loading,
    error,
    targetLang,
    setTargetLang,
    translate,
    clear,
  } = useAITranslation();

  const [showTranslate, setShowTranslate] = useState(false);

  const handleTranslate = useCallback(
    (lang) => {
      translate(pageText, lang);
    },
    [translate, pageText]
  );

  const handleLangChange = useCallback(
    (e) => {
      setTargetLang(e.target.value);
      if (showTranslate) translate(pageText, e.target.value);
    },
    [setTargetLang, showTranslate, translate, pageText]
  );

  const toggleTranslate = useCallback(() => {
    if (showTranslate) {
      setShowTranslate(false);
      clear();
    } else {
      setShowTranslate(true);
      handleTranslate(targetLang);
    }
  }, [showTranslate, clear, handleTranslate, targetLang]);

  if (!mode) return null;

  const btnLabel = mode === 'gemini' ? 'AI Translate' : 'Translate';
  const resultSize = Math.max(16, fontSize - 8);
  const contentFontFamily =
    fontFamily === 'serif' ? "'Playfair Display', serif" : 'Inter, sans-serif';

  return (
    <div className="w-full max-w-5xl flex flex-col gap-3">
      {/* ── Toolbar ── */}
      <div className="flex flex-wrap items-center gap-2">
        <select
          value={targetLang}
          onChange={handleLangChange}
          className={`text-xs rounded-lg border px-2 py-1.5 transition focus:outline-none ${btnCls} ${selectBg}`}
        >
          {LANGUAGES.map(({ code, label }) => (
            <option key={code} value={code} className="bg-[#1a1a1a] text-white">
              {label}
            </option>
          ))}
        </select>
        <button
          onClick={toggleTranslate}
          title="Translate with on-device AI (Google Gemini Nano)"
          className={`px-3 py-1.5 rounded-lg border active:scale-95 transition text-xs whitespace-nowrap ${
            showTranslate
              ? 'border-amber-500 text-amber-400 bg-amber-500/10'
              : btnCls
          }`}
        >
          {loading ? (
            <>
              <FontAwesomeIcon icon={faSpinner} spin className="mr-1" />
              Translating…
            </>
          ) : (
            <>
              <FontAwesomeIcon icon={faGlobe} className="mr-1" />
              {btnLabel}
            </>
          )}
        </button>
        <span className="hidden sm:inline text-[10px] text-white/25 ml-auto whitespace-nowrap">
          Gemini Nano · on-device
        </span>
      </div>

      {/* ── Result panel ── */}
      {showTranslate && (
        <div className="rounded-2xl border border-amber-500/30 bg-amber-500/5 px-5 sm:px-8 py-5 flex flex-col gap-3">
          {mode === 'gemini' && (
            <p className="text-[11px] text-amber-400/60 leading-tight">
              <FontAwesomeIcon icon={faTriangleExclamation} className="mr-1" />
              Translation generated by{' '}
              <strong className="text-amber-400/80">
                Google Gemini Nano
              </strong>{' '}
              running on-device. May contain errors — the website bears{' '}
              <strong className="text-amber-400/80">no responsibility</strong>{' '}
              for mistranslations. Always verify with a trusted Bible
              translation.
            </p>
          )}
          {loading && (
            <p
              className="text-amber-300 animate-pulse text-center py-4"
              style={{ fontSize: resultSize }}
            >
              Translating…
            </p>
          )}
          {error && <p className="text-red-400 text-sm">{error}</p>}
          {translation && !loading && (
            <p
              className="text-amber-100 leading-snug"
              style={{
                fontSize: resultSize,
                fontFamily: contentFontFamily,
                fontWeight: 400,
                lineHeight: 1.6,
              }}
            >
              {translation}
            </p>
          )}
        </div>
      )}
    </div>
  );
}
